name: cutree
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  cloud_firestore:
  flutter_neumorphic:
  firebase_auth:
  material_design_icons_flutter:
  google_fonts:
  provider:
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/welcome.png
    - assets/images/logo.png
    - assets/images/haircut.png
    - assets/images/shave.jpeg
    - assets/images/beard_trim.png
    - assets/images/salon_images/salon_1.jpg
